# Generated by Django 3.0.8 on 2020-09-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costo_utilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo_etecsa', models.FloatField(verbose_name='Costo Etecsa')),
                ('utilidad_diaria', models.FloatField(verbose_name='Utilidad Diaria')),
            ],
        ),
        migrations.CreateModel(
            name='rtv_cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant_c', models.IntegerField(verbose_name='Cantidad de 5')),
                ('cant_d', models.IntegerField(verbose_name='Cantidad de 10')),
                ('cant_v', models.IntegerField(verbose_name='Cantidad de 20')),
                ('valor_facial', models.FloatField(verbose_name='Valor Facial')),
                ('valor_etecsa', models.FloatField(verbose_name='Valor Etecsa')),
                ('ingreso_ag', models.FloatField(verbose_name='Ingreso A.G')),
            ],
        ),
        migrations.CreateModel(
            name='rtv_movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant_c', models.IntegerField(verbose_name='Total: Cantidad de 5')),
                ('cant_d', models.IntegerField(verbose_name='Total: Cantidad de 10')),
                ('cant_v', models.IntegerField(verbose_name='Total: Cantidad de 20')),
                ('valor_facial', models.FloatField(verbose_name='Valor Facial')),
                ('valor_etecsa', models.FloatField(verbose_name='Valor Etecsa')),
                ('ingreso_ag_cup', models.FloatField(verbose_name='Ingreso A.G-CUP')),
            ],
        ),
        migrations.CreateModel(
            name='rtv_nauta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant_dos', models.IntegerField(verbose_name='Total: Cantidad de 2')),
                ('cant_c', models.IntegerField(verbose_name='Total: Cantidad de 5')),
                ('cant_d', models.IntegerField(verbose_name='Total: Cantidad de 10')),
                ('valor_facial', models.FloatField(verbose_name='Valor Facial')),
                ('valor_etecsa', models.FloatField(verbose_name='Valor Etecsa')),
                ('ingreso_ag_cup', models.FloatField(verbose_name='Ingreso A.G-CUP')),
            ],
        ),
        migrations.CreateModel(
            name='t_anual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant_c', models.IntegerField(verbose_name='Total: Cantidad de 5')),
                ('cant_d', models.IntegerField(verbose_name='Total: Cantidad de 10')),
                ('cant_v', models.IntegerField(verbose_name='Total: Cantidad de 20')),
                ('valor_facial', models.FloatField(verbose_name='Total: Valor Facial')),
                ('valor_etecsa', models.FloatField(verbose_name='Total: Valor Etecsa')),
                ('ingreso_ag', models.FloatField(verbose_name='Total: Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='t_anual_movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant_c', models.IntegerField(verbose_name='Total: Cantidad de 5')),
                ('cant_d', models.IntegerField(verbose_name='Total: Cantidad de 10')),
                ('cant_v', models.IntegerField(verbose_name='Total: Cantidad de 20')),
                ('valor_facial', models.FloatField(verbose_name='Total: Valor Facial')),
                ('valor_etecsa', models.FloatField(verbose_name='Total: Valor Etecsa')),
                ('ingreso_ag_cup', models.FloatField(verbose_name='Total: Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='t_anual_nauta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant_dos', models.IntegerField(verbose_name='Total: Cantidad de 2')),
                ('cant_c', models.IntegerField(verbose_name='Total: Cantidad de 5')),
                ('cant_d', models.IntegerField(verbose_name='Total: Cantidad de 10')),
                ('valor_facial', models.FloatField(verbose_name='Total: Valor Facial')),
                ('valor_etecsa', models.FloatField(verbose_name='Total: Valor Etecsa')),
                ('ingreso_ag_cup', models.FloatField(verbose_name='Total: Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='trtv_cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tcant_c', models.IntegerField(verbose_name='Total: Cantidad de 5')),
                ('tcant_d', models.IntegerField(verbose_name='Total: Cantidad de 10')),
                ('tcant_v', models.IntegerField(verbose_name='Total: Cantidad de 20')),
                ('tvalor_facial', models.FloatField(verbose_name='Total: Valor Facial')),
                ('tvalor_etecsa', models.FloatField(verbose_name='Total: Valor Etecsa')),
                ('tingreso_ag', models.FloatField(verbose_name='Total: Ingreso')),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='', max_length=50)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='trtv_movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tcant_c', models.IntegerField(verbose_name='Total: Cantidad de 5')),
                ('tcant_d', models.IntegerField(verbose_name='Total: Cantidad de 10')),
                ('tcant_v', models.IntegerField(verbose_name='Total: Cantidad de 20')),
                ('tvalor_facial', models.FloatField(verbose_name='Total: Valor Facial')),
                ('tvalor_etecsa', models.FloatField(verbose_name='Total: Valor Etecsa')),
                ('tingreso_ag_cup', models.FloatField(verbose_name='Total: Ingreso A.G-CUP')),
                ('mes', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='trtv_nauta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tcant_dos', models.IntegerField(verbose_name='Total: Cantidad de 2')),
                ('tcant_c', models.IntegerField(verbose_name='Total: Cantidad de 5')),
                ('tcant_d', models.IntegerField(verbose_name='Total: Cantidad de 10')),
                ('tvalor_facial', models.FloatField(verbose_name='Total: Valor Facial')),
                ('tvalor_etecsa', models.FloatField(verbose_name='Total: Valor Etecsa')),
                ('tingreso_ag_cup', models.FloatField(verbose_name='Total: Ingreso A.G-CUP')),
                ('mes', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
