# Generated by Django 3.0.6 on 2020-06-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costo_utilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_etecsa', models.FloatField()),
                ('utilidad_diaria', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='rtv_cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant', models.IntegerField()),
                ('valor_facial', models.FloatField()),
                ('valor_etecsa', models.FloatField()),
                ('ingreso_ag', models.FloatField()),
                ('tcant', models.IntegerField()),
                ('tvalor_facial', models.FloatField()),
                ('tvalor_etecsa', models.FloatField()),
                ('tingreso_ag', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='rtv_movil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant', models.IntegerField()),
                ('valor_facial', models.FloatField()),
                ('valor_etecsa', models.FloatField()),
                ('ingreso_ag_cuc', models.FloatField()),
                ('ingreso_ag_cup', models.FloatField()),
                ('tcant', models.IntegerField()),
                ('tvalor_facial', models.FloatField()),
                ('tvalor_etecsa', models.FloatField()),
                ('tingreso_ag_cuc', models.FloatField()),
                ('tingreso_ag_cup', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='rtv_nauta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant', models.IntegerField()),
                ('valor_facial', models.FloatField()),
                ('valor_etecsa', models.FloatField()),
                ('ingreso_ag_cuc', models.FloatField()),
                ('ingreso_ag_cup', models.FloatField()),
                ('tcant', models.IntegerField()),
                ('tvalor_facial', models.FloatField()),
                ('tvalor_etecsa', models.FloatField()),
                ('tingreso_ag_cuc', models.FloatField()),
                ('tingreso_ag_cup', models.FloatField()),
            ],
        ),
    ]
