# Generated by Django 3.0.8 on 2020-09-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PbApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('factura', models.FloatField(verbose_name='Factura')),
                ('comision', models.FloatField(verbose_name='Comisión')),
            ],
        ),
        migrations.CreateModel(
            name='t_facturaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tfactura', models.FloatField(verbose_name='Total de Factura')),
                ('tcomision', models.FloatField(verbose_name='Total de Comisión')),
            ],
        ),
    ]
