# Generated by Django 3.0.8 on 2021-02-15 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PbApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('factura', models.FloatField(verbose_name='Factura')),
                ('comision', models.FloatField(verbose_name='Comisión')),
            ],
        ),
        migrations.CreateModel(
            name='onat_etecsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('pagar_en_onat', models.FloatField(verbose_name='Pagar en la Onat')),
                ('pagado_en_onat', models.FloatField(blank=True, null=True, verbose_name='Pagado en la Onat')),
            ],
        ),
        migrations.CreateModel(
            name='t_anual_facturaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('factura', models.FloatField(verbose_name='Factura')),
                ('comision', models.FloatField(verbose_name='Comisión')),
            ],
        ),
        migrations.CreateModel(
            name='t_facturaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tfactura', models.FloatField(verbose_name='Total de Factura')),
                ('tcomision', models.FloatField(verbose_name='Total de Comisión')),
                ('mes', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='t_onat_etecsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('t_ingreso', models.FloatField(verbose_name='Total Ingreso')),
                ('imp_seg_ingreso', models.FloatField(verbose_name='Impuesto segun ingreso')),
                ('ft_ssocial', models.FloatField(verbose_name='Fuerza de Trabajo y Seguridad Social')),
                ('pagar_en_onat', models.FloatField(verbose_name='Pagar en la Onat')),
                ('pagado_en_onat', models.FloatField(verbose_name='Pagado en la Onat')),
                ('diferencia', models.FloatField(verbose_name='Diferencia')),
            ],
        ),
    ]
