# Generated by Django 3.0.6 on 2020-06-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PbApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_anual',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='t_anual_movil',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='t_anual_nauta',
            name='mes',
        ),
    ]
