# Generated by Django 3.0.8 on 2020-09-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PbApp', '0002_facturaciones_t_facturaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_facturaciones',
            name='mes',
            field=models.CharField(default='', max_length=50),
        ),
    ]
