# Generated by Django 3.0.8 on 2021-02-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PbApp', '0002_facturaciones_onat_etecsa_t_anual_facturaciones_t_facturaciones_t_onat_etecsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onat_etecsa',
            name='pagar_en_onat',
            field=models.FloatField(blank=True, null=True, verbose_name='Pagar en la Onat'),
        ),
    ]
