# Generated by Django 3.0.6 on 2020-06-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PbApp', '0002_auto_20200627_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='trtv_movil',
            name='mes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trtv_nauta',
            name='mes',
            field=models.CharField(default='', max_length=50),
        ),
    ]
