# Generated by Django 3.0.6 on 2020-07-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PbApp', '0003_auto_20200627_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='meses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess', models.CharField(max_length=50)),
            ],
        ),
    ]
