# Generated by Django 3.0.8 on 2020-09-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PbApp', '0003_t_facturaciones_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_anual_facturaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('factura', models.FloatField(verbose_name='Factura')),
                ('comision', models.FloatField(verbose_name='Comisión')),
            ],
        ),
    ]
