# Generated by Django 3.0.8 on 2020-09-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PbApp', '0004_t_anual_facturaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='onat_etecsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_ingreso', models.FloatField(verbose_name='Total Ingreso')),
                ('imp_seg_ingreso', models.FloatField(verbose_name='Impuesto segun ingreso')),
                ('ft_ssocial', models.FloatField(verbose_name='Fuerza de Trabajo y Seguridad Social')),
                ('pagar_en_onat', models.FloatField(verbose_name='Pagar en la Onat')),
                ('pagado_en_onat', models.FloatField(verbose_name='Pagado en la Onat')),
                ('diferencia', models.FloatField(verbose_name='Diferencia')),
                ('mes', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='t_onat_etecsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_ingreso', models.FloatField(verbose_name='Total Ingreso')),
                ('imp_seg_ingreso', models.FloatField(verbose_name='Impuesto segun ingreso')),
                ('ft_ssocial', models.FloatField(verbose_name='Fuerza de Trabajo y Seguridad Social')),
                ('pagar_en_onat', models.FloatField(verbose_name='Pagar en la Onat')),
                ('pagado_en_onat', models.FloatField(verbose_name='Pagado en la Onat')),
                ('diferencia', models.FloatField(verbose_name='Diferencia')),
            ],
        ),
    ]
